version: "3.7"

services:
  backend:
    build: ./test_api
    ports:
      - "8000:8000"
    restart: always
  frontend:
    container_name: front
    build:
      context: ./frontend
    ports:
        - "3000:3000"
